apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: paw-reaktiver-arbeidssoker
    namespace: paw
    labels:
        team: paw
spec:
    azure:
        application:
            enabled: true
    image: {{ image }}
    port: 3000
    replicas:
        min: 1
        max: 1
    env:
        - name: APP_NAME
          value: paw-reaktiver-arbeidssoker
        - name: KAFKA_TOPIC
          value: meldekort.aapen-meldeplikt-meldekortgodkjentalle-v1-p
        - name: AIA_BACKEND_SCOPE
          value: api://prod-gcp.paw.aia-backend/.default
        - name: VEILARBREGISTRERING_GCP_SCOPE
          value: api://prod-gcp.paw.veilarbregistrering/.default
        - name: PAW_PROXY_SCOPE
          value: api://prod-fss.paw.paw-proxy/.default
        - name: VEILARBREGISTRERING_URL
          value: https://paw-proxy.prod-fss-pub.nais.io/veilarbregistrering
        - name: VEILARBREGISTRERING_GCP_URL
          value: http://veilarbregistrering/veilarbregistrering
        - name: AIA_BACKEND_URL
          value: http://aia-backend/aia-backend
        - name: UNLEASH_API_URL
          value: https://unleash.nais.io/api/
        - name: UNLEASH_ENVIRONMENT
          value: prod
    resources:
        limits:
            cpu: '3'
            memory: 768Mi
        requests:
            cpu: 500m
            memory: 580Mi
    kafka:
        pool: nav-prod
    accessPolicy:
        outbound:
            rules:
                - application: aia-backend
                - application: veilarbregistrering
                - application: dp-innsyn
                  namespace: teamdagpenger
                - application: paw-proxy
                  cluster: prod-fss
