apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: paw-reaktiver-arbeidssoker
    namespace: paw
    labels:
        team: paw
spec:
    azure:
        application:
            enabled: true
    image: { { image } }
    port: 3000
    replicas:
        min: 1
        max: 1
    liveness:
        path: /isAlive
        initialDelay: 10
    readiness:
        path: /isReady
        initialDelay: 10
    prometheus:
        enabled: true
        path: /prometheus
    env:
        - name: APP_NAME
          value: paw-reaktiver-arbeidssoker
        - name: KAFKA_TOPIC
          value: paw.testplayground
        - name: AIA_BACKEND_SCOPE
          value: api://dev-gcp.paw.aia-backend/.default
        - name: VEILARBREGISTRERING_SCOPE
          value: api://dev-gcp.paw.veilarbregistrering/.default
        - name: VEILARBREGISTRERING_URL
          value: http://veilarbregistrering/veilarbregistrering
        - name: AIA_BACKEND_URL
          value: http://aia-backend/aia-backend
        - name: UNLEASH_API_URL
          value: https://unleash.nais.io/api/
        - name: UNLEASH_ENVIRONMENT
          value: dev
        - name: UNLEASH_SERVER_API_URL
          value: https://paw-unleash-api.nav.cloud.nais.io/api
    resources:
        limits:
            cpu: 500m
            memory: 512Mi
        requests:
            cpu: 200m
            memory: 256Mi
    kafka:
        pool: nav-dev
    accessPolicy:
        outbound:
            external:
                - host: paw-unleash-api.nav.cloud.nais.io
            rules:
                - application: aia-backend
                - application: veilarbregistrering
                - application: paw-proxy
                  cluster: dev-fss
