apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: paw-reaktiver-arbeidssoker
    namespace: paw
    labels:
        team: paw
spec:
    image: {{ image }}
    port: 3000
    replicas:
        min: 1
        max: 1
    env:
        - name: KAFKA_TOPIC
          value: testplayground
    resources:
        limits:
            cpu: '3'
            memory: 768Mi
        requests:
            cpu: 500m
            memory: 580Mi
    kafka:
      pool: nav-dev
    accessPolicy:
        outbound:
            rules:
                - application: aia-backend
                  namespace: paw
