apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: paw-reaktiver-arbeidssoker-unleash
  namespace: paw
  labels:
    "team": "paw"
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: paw
  secretName:  paw-reaktiver-arbeidssoker-unleash-api-token
  environment: development
