name: Build, push, and deploy

on:
    push:
        branches:
            - main
            - dev/*

jobs:
    test-build-and-push:
        name: Test, build and push
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: docker-build-push
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                  team: paw
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}

    deploy-dev:
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
        name: Deploy til dev
        permissions:
          contents: 'read'
          id-token: 'write'
        needs: [test-build-and-push]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  IMAGE: ${{ needs.test-build-and-push.outputs.image }}
                  RESOURCE: nais/dev-gcp/nais.yaml

    deploy-prod:
        if: github.ref == 'refs/heads/main'
        name: Deploy til prod
        permissions:
          contents: 'read'
          id-token: 'write'
        needs: [test-build-and-push, deploy-dev]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: nais/prod-gcp/nais.yaml
                  IMAGE: ${{ needs.test-build-and-push.outputs.image }}

    apply-apitoken-unleash:
        name: Legger til ApiToken for Unleash
        permissions:
          contents: 'read'
          id-token: 'write'
        runs-on: ubuntu-latest
        needs: [test-build-and-push]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: deploy to dev
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: nais/dev-gcp/unleash-apitoken.yaml
            - name: deploy to prod
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: nais/prod-gcp/unleash-apitoken.yaml
